spring:
  profiles:
    # 切换配置文件
    active: @profiles.active@

# sa-token
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: 'Authorization'
  # token风格
  token-style: 'tik'
  # token前缀
  token-prefix: 'Bearer'
  # token有效期，单位秒 默认30天，不支持自动续签
  timeout: 259200
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒，支持自动续签
  activity-timeout: 1800
  # 自动续签，指定时间内有操作，则会自动续签
  auto-renew: true
  # 是否尝试从header里读取token
  is-read-head: true
  # 是否尝试从cookie里读取token
  is-read-cookie: false
  # 是否尝试从请求体里读取token
  is-read-body: false
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # 是否在初始化配置时打印版本字符画
  is-print: true
  # 是否输出操作日志
  is-log: true
  # 独立Redis插件
  alone-redis:
    host: ${spring.redis.host}
    port: ${spring.redis.port}
    password: ${spring.redis.password}
    # 数据库索引
    database: 1
    # 连接超时时间
    timeout: ${spring.redis.timeout}
    lettuce:
      pool:
        # 连接池中的最大空闲连接数
        max-idle: ${spring.redis.lettuce.pool.max-idle}
        # 连接池中的最小空闲连接数
        min-idle: ${spring.redis.lettuce.pool.min-idle}
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: ${spring.redis.lettuce.pool.max-active}
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: ${spring.redis.lettuce.pool.max-wait}
