spring:
  # 数据源配置
  datasource:
    # 连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库名称
    database: asurplus-vue
    port: 3306
    url: jdbc:mysql://${server.host}:${spring.datasource.port}/${spring.datasource.database}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=true&characterEncoding=UTF-8
    username: root
    password: 6666
    # druid相关配置
    druid:
      # 初始化时建立物理连接的个数
      initial-size: 5
      # 最大连接池数量
      max-active: 20
      # 最小连接池数量
      min-idle: 10
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 300000
      # 用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 1 FROM DUAL
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭
      pool-prepared-statements: false
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
      max-pool-prepared-statement-per-connection-size: 50
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
      filter:
        stat:
          enabled: true
          # 慢sql记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 用户名密码
        login-username: admin
        login-password: 123456
  # Redis配置
  redis:
    host: ${server.host}
    port: 6379
    password:
    # 数据库索引
    database: 0
    # 连接超时时间（毫秒）
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最大空闲连接数
        max-idle: 8
        # 连接池中的最小空闲连接数
        min-idle: 0
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
  # jackson 配置
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 上传文件
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    # 切换配置文件
    active: dev

# sa-token
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: 'Authorization'
  # token风格
  token-style: 'tik'
  # token前缀
  token-prefix: 'Bearer'
  # token有效期，单位秒 默认30天，不支持自动续签
  timeout: 259200
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒，支持自动续签
  activity-timeout: 1800
  # 自动续签，指定时间内有操作，则会自动续签
  auto-renew: true
  # 是否尝试从header里读取token
  is-read-head: true
  # 是否尝试从cookie里读取token
  is-read-cookie: false
  # 是否尝试从请求体里读取token
  is-read-body: false
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # 是否在初始化配置时打印版本字符画
  is-print: true
  # 是否输出操作日志
  is-log: true
  # 独立Redis插件
  alone-redis:
    host: ${spring.redis.host}
    port: ${spring.redis.port}
    password: ${spring.redis.password}
    # 数据库索引
    database: 1
    # 连接超时时间
    timeout: ${spring.redis.timeout}
    lettuce:
      pool:
        # 连接池中的最大空闲连接数
        max-idle: ${spring.redis.lettuce.pool.max-idle}
        # 连接池中的最小空闲连接数
        min-idle: ${spring.redis.lettuce.pool.min-idle}
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: ${spring.redis.lettuce.pool.max-active}
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: ${spring.redis.lettuce.pool.max-wait}
